# Generated by Django 3.0.4 on 2020-03-28 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitter', '0003_auto_20200328_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='child_sitter', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
