# Generated by Django 3.0.4 on 2020-04-13 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sitter', '0005_auto_20200328_1310'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('decease', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_mail', models.EmailField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requests', models.ManyToManyField(to='sitter.Sitter')),
            ],
        ),
    ]
