# Generated by Django 3.0.4 on 2020-04-13 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_asd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asd',
        ),
    ]
